on: [push, pull_request]

jobs:
  stm32_ci_job:
    runs-on: ubuntu-latest
    name: CI job for stm32
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: CI action step for stm32
      id: stm32ci
      uses: milesfrain/stm32-action@v0.5

